mysite/food/urls.py
from . import views
from django.urls import path

app_name = "food"
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    # path('<int:item_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    # path('add/', views.create_item, name='create_item'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:id>', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_view.register, name="register"),
    path('login/',authentication_views.LoginView.as_view(template_name = 'users/login.html'), name="login"),
    path('logout/', user_view.logout_view, name='logout'),
    path('profile/', user_view.profilepage, name='profile'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://theme-assets.getbento.com/sensei/74ec6d7.sensei/assets/images/catering-item-placeholder-704x520.png")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpeg', upload_to='profile_picture')
    location = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.forms import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Item
from .forms import ItemForm

# Class based view
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

def index(request):
    items = Item.objects.all()
    context = {
        'items':items
    }
    return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def detail(request, item_id):
    item = Item.objects.get(pk = item_id)
    context = {
        'item': item,
    }
    return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)



def update_item(request, id):
    item = Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form, 'item': item})

def delete_item(request, id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html')

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .froms import RegisterForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hello {username}, Your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return render(request, 'users/logout.html')

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href={% static "food/style.css" %}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url "food:index" %}" class="navbar-brand">Food App</a>
        <div class="navbar">
            <a href="{% url "food:create_item" %}" class="nav-item nav-link">Add Item</a>
            <a href="#" class="nav-item nav-link">Delete Item</a>
            <a href="#" class="nav-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url "profile" %}" class="nav-item nav-link">Profile</a>
                <a href="{% url "logout" %}" class="nav-item nav-link">Logout</a>
            {% else %}
                <a href="{% url "login" %}" class="nav-item nav-link">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% block body %}
    
    {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ object.item_image }}" alt="" class="card" height="300px">
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>   
            <h3>${{ object.item_price }}</h3>
            <a href="{% url "food:delete_item" object.id %}" class="btn danger">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/food/templates/food/index.html
{% extends "food/base.html" %}   
    {% block body %}

    {% for item in items %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img src="{{item.item_image}}" alt="" class="card" height="150px" width="200px">
        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h5>${{ item.item_price }}</h5>
            <h5>Posted by : {{ item.user_name }}</h5>
        </div>
        <div class="col-md-2">
            <a href="{% url "food:detail" item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

mysite/food/templates/food/item-delete.html
{% extends "food/base.html" %}
{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

mysite/food/templates/food/item-form.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card">
                <div class="card-header">
                    Add New Item
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/users/templates/users/login.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                        <br>
                        <br>
                        <p>Don't have an account ? <a href="{% url "register" %}">Signup Here</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}




{% comment %} <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form> {% endcomment %}

mysite/users/templates/users/logout.html
<h1>Logged out</h1>

mysite/users/templates/users/profile.html
{% extends "food/base.html" %}
{% block body %}
<h1> {{ user.username }} </h1>
<img src="{{ user.profile.image.url }}" alt="Not loaded">
{% endblock %}

mysite/users/templates/users/register.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <br>
                        <button class="btn-info" type="submit">Signup</button>
                        <br>
                        <br>
                        <p>Already have an account ? <a href="{% url "login" %}">Login Here</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}